services:
  caddy:
    image: caddy:2-alpine
    container_name: windows-util-scripts
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ../scripts:/srv/scripts:ro
      - ./:/srv/lan:ro
      - ./:/etc/caddy:ro
