#Requires -Version 5.1
<#
.SYNOPSIS
    Export public-safe WPF launcher files to a private LAN script folder.

.DESCRIPTION
    Copies the shared WPF engine and writes LAN launcher bootstraps into a
    private folder served by LAN Caddy/NAS. This does not copy private scripts,
    credentials, .env files, or Git metadata.
#>

param(
    [Parameter(Mandatory)]
    [string]$DestinationPath,

    [string]$LanBaseUrl = "https://get.home.us",

    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$destination = [IO.Path]::GetFullPath($DestinationPath)
$libDestination = Join-Path $destination 'lib'

if (-not (Test-Path -LiteralPath $destination)) {
    New-Item -ItemType Directory -Path $destination -Force | Out-Null
}
if (-not (Test-Path -LiteralPath $libDestination)) {
    New-Item -ItemType Directory -Path $libDestination -Force | Out-Null
}

Copy-Item -LiteralPath (Join-Path $repoRoot 'lib\wpf-menu-engine.ps1') `
    -Destination (Join-Path $libDestination 'wpf-menu-engine.ps1') -Force

$normalizedLanBaseUrl = $LanBaseUrl.TrimEnd('/')
$bootstrap = @"
#Requires -Version 5.1
<#
.SYNOPSIS
    LAN bootstrapper for the shared WPF Windows Setup Toolkit engine.

.DESCRIPTION
    Intended LAN entry point:

        irm $normalizedLanBaseUrl/launcher | iex

    This file is generated by tools/export-lan-launcher.ps1.
#>

param(
    [string]`$LanBaseUrl = "$normalizedLanBaseUrl",
    [string]`$WanBaseUrl = "https://get.tand.us"
)

Set-StrictMode -Version Latest
`$ErrorActionPreference = 'Stop'
`$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

`$base = `$LanBaseUrl.TrimEnd('/')
`$engine = Invoke-RestMethod -Uri "`$base/lib/wpf-menu-engine.ps1" -UseBasicParsing
& ([scriptblock]::Create(`$engine)) -Mode LAN -LanBaseUrl `$base -BaseUrl `$base -WanBaseUrl `$WanBaseUrl -OfflinePreferred
"@

foreach ($name in @('launcher', 'launcher.ps1')) {
    $target = Join-Path $destination $name
    if ((Test-Path -LiteralPath $target) -and -not $Force) {
        Write-Host "Keeping existing $target. Use -Force to overwrite." -ForegroundColor Yellow
        continue
    }
    Set-Content -LiteralPath $target -Value $bootstrap -Encoding UTF8
    Write-Host "Wrote $target"
}

$manifestExample = Join-Path $destination 'lan-manifest.example.json'
if (-not (Test-Path -LiteralPath $manifestExample) -or $Force) {
    Copy-Item -LiteralPath (Join-Path $repoRoot 'examples\private-script-source\lan-manifest.json') `
        -Destination $manifestExample -Force
    Write-Host "Wrote $manifestExample"
}

if (-not (Test-Path -LiteralPath (Join-Path $destination 'lan-manifest.json'))) {
    Write-Host "No lan-manifest.json exists in $destination. Create one from lan-manifest.example.json." -ForegroundColor Yellow
}

Write-Host "LAN launcher export complete: $destination" -ForegroundColor Green
